function f = myfun1(fp,s)
figure
subplot(331)
imshow(fp)
title(s)
subplot(332)
imshow(spfilt(fp,'amean'))
title('算数均值')
subplot(333)
imshow(spfilt(fp,'gmean'))
title('几何均值')
subplot(334)
imshow(spfilt(fp,'chmean'))
title('Q为1.5的逆调和均值')
subplot(335)
imshow(spfilt(fp,'chmean',3,3,-1.5))
title('Q为-1.5的逆调和均值')
subplot(336)
imshow(spfilt(fp,'atrimmed'))
title('d为2的修正均值')
subplot(337)
imshow(adpmedian(fp,7)),title('自适应均值滤波')
end

