%分别使用conv和filter函数计算h和x的卷积y和y1，运行程序
% Program P2_7
clf;
h = [3 2 1 -2 1 0 -4 0 3]; %impulse response
x = [1 -2 3 -4 3 2 1]; %input sequence

%使用conv求卷积,并使用stem画图
y = conv(h,x);
n = 0:14;%m+n-1
subplot(2,1,1);
stem(n,y);
xlabel('Time index n'); ylabel('Amplitude');
title('Output Obtained by Convolution'); grid;


x1 = [x zeros(1,8)];
y1 = filter(h,1,x1);
subplot(2,1,2);
stem(n,y1);
xlabel('Time index n'); ylabel('Amplitude');
 title('Output Generated by Filtering'); grid; 
